name: City Council Docs

on:
  schedule:
    - cron: '0 0 * * 0' # 12:00 AM UTC every Sunday
  workflow_dispatch:

jobs:
  sync-docs:
    runs-on: ubuntu-latest
    outputs:
      changes_detected: ${{ steps.commit.outputs.changes_detected }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: robinraju/release-downloader@v1
        with:
          repository: dntiontk/civic-code
          latest: true
          fileName: doc-search-linux
      - name: Run doc-search
        run: |
          chmod +x doc-search-linux
          ./doc-search-linux > content/city-council-docs/documents.json
          rm doc-search-linux
      - name: Update lastSyncDate
        run: |
          lastSync=$(date -u +%F)
          sed -i "s/lastSyncDate: .*/lastSyncDate: \"$lastSync\"/" content/city-council-docs/index.md
      - uses: stefanzweifel/git-auto-commit-action@v5
        id: commit
        with:
          commit_message: sync city-council docs
          file_pattern: content/city-council-docs/*
  deploy-site:
    needs: sync-docs
    if: needs.sync-docs.outputs.changes_detected == 'true'
    uses: ./.github/workflows/hugo.yml